services:
  - type: web
    name: arcaneering-calculator
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn web_calculator:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0